# Generated by Django 5.2.4 on 2025-07-21 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('transferred', 'Transferido'), ('inactive', 'Desligado'), ('suspended', 'Suspenso')], default='active', max_length=20, verbose_name='Status')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro')], null=True, verbose_name='Gênero')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Data de ingresso')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações internas')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
