# Generated by Django 5.2.4 on 2025-07-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cpf',
        ),
    ]
