# Generated by Django 5.2.4 on 2025-07-24 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsibles', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0003_remove_student_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='responsibles',
            field=models.ManyToManyField(related_name='students', to='responsibles.responsible'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
            preserve_default=False,
        ),
    ]
