# Generated by Django 5.2.4 on 2025-07-24 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.CharField(choices=[('mother', 'Mãe'), ('father', 'Pai'), ('tutor', 'Tutor(a)'), ('avos', 'Avô/Avó'), ('irmao', 'Irmão(ã)'), ('outro', 'Outro')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
