# Generated by Django 5.2.4 on 2025-07-24 03:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, verbose_name='Nome da turma: 0ª ANO')),
                ('year', models.PositiveIntegerField(verbose_name='Ano letivo')),
                ('room_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identificação da sala (opcional)')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações Internas (opcional)')),
                ('period', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('evening', 'Noite'), ('full', 'Integral')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
