# Generated by Django 5.2.4 on 2025-07-24 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_classroom', to=settings.AUTH_USER_MODEL),
        ),
    ]
